### ISSUE TITLE
docker Dockerfile 搭建遇到digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by DingBool** [AaronYES/UnblockNeteaseMusic#1]
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/eapi/batch.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (node:internal/crypto/cipher:193:29)
        at decrypt (/app/app.js:50:56)
        at Object.decrypt (/app/app.js:52:90)
        at /app/app.js:98:163
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

**Comment by AaronYES** [comment]
我这个仓库是我之前研究学习的 可能有很多问题

建议使用这个仓库
https://github.com/UnblockNeteaseMusic/server

**Comment by DingBool** [comment]
好的谢谢，我去看看
